version: '3.1'
services:
  nexus:
    image: sonatype/nexus3
#    ports:
#      - 8443:8443
    networks:
      - proxy
    volumes:
      - ${USC_LOCAL_DIR}/nexus:/nexus-data
#    secrets:
#      - keystore.jks
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=nexus.docker.usc.edu
        - com.df.httpsOnly=true
        - com.df.port=8081
        - com.df.xForwardedProto=true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==${NODE01}
#    environment:
#      - INSTALL4J_ADD_VM_PARAMS=-DJETTY_PASSWORD=${USC_NEXUS_KEYSTORE_PASSWORD}
networks:
  proxy:
    external:
      name: proxy
# secrets:
#  keystore.jks:
#    external: true
