version: '3.1'
services:
  nexus:
    image: uscdev/nexus
    ports:
      - 8443:8443
    networks:
      - proxy
    volumes:
      - nexus-data:/nexus-data
    secrets:
      - keystore.jks
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=nexus.swarm.usc.edu
        - com.df.httpsOnly=true
        - com.df.port=8081
        - com.df.xForwardedProto=true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-DJETTY_PASSWORD=${USC_NEXUS_KEYSTORE_PASSWORD}
networks:
  proxy:
    external:
      name: proxy
secrets:
  keystore.jks:
    external: true
volumes:
  nexus-data:
    external: true
